import keyMirror from 'keymirror';

export default keyMirror({
  QUESTION_CREATE: null,
  EDIT_QUESTION: null,
  QUESTION_DELETE: null,
  UPDATE_LOADER_STATUS: null,
  LOAD_QUESTION_SUCCESS: null,
  LOAD_QUESTION_ERROR: null,
  LOAD_QUESTIONS_SUCCESS: null,
  LOAD_TOP_QUESTIONS_SUCCESS: null,
  FILTER_QUESTIONS_WITH_TAGS: null,
  LOAD_USER_QUESTIONS_SUCCESS: null,
  UPDATE_QUESTION_VOTE_SUCCESS: null
});
